import type { TableTheme } from '../types';

export const THEME_PRESETS: TableTheme[] = [
  {
    id: 'default',
    name: 'Clean Slate',
    headerBg: '#1e293b',
    headerText: '#ffffff',
    cellBg: '#ffffff',
    cellText: '#1e293b',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#f8fafc',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '600',
    borderRadius: 8,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'midnight',
    name: 'Midnight',
    headerBg: '#0f172a',
    headerText: '#e2e8f0',
    cellBg: '#1e293b',
    cellText: '#cbd5e1',
    borderColor: '#334155',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#1a2332',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '600',
    borderRadius: 8,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'ocean',
    name: 'Ocean Blue',
    headerBg: '#0369a1',
    headerText: '#ffffff',
    cellBg: '#f0f9ff',
    cellText: '#0c4a6e',
    borderColor: '#bae6fd',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#e0f2fe',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '600',
    borderRadius: 8,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'forest',
    name: 'Forest Green',
    headerBg: '#166534',
    headerText: '#ffffff',
    cellBg: '#f0fdf4',
    cellText: '#14532d',
    borderColor: '#bbf7d0',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#dcfce7',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '600',
    borderRadius: 8,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'sunset',
    name: 'Sunset',
    headerBg: '#c2410c',
    headerText: '#ffffff',
    cellBg: '#fff7ed',
    cellText: '#7c2d12',
    borderColor: '#fed7aa',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#ffedd5',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '600',
    borderRadius: 8,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'royal',
    name: 'Royal Purple',
    headerBg: '#6b21a8',
    headerText: '#ffffff',
    cellBg: '#faf5ff',
    cellText: '#581c87',
    borderColor: '#d8b4fe',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#f3e8ff',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '600',
    borderRadius: 8,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'rose',
    name: 'Rose',
    headerBg: '#be123c',
    headerText: '#ffffff',
    cellBg: '#fff1f2',
    cellText: '#881337',
    borderColor: '#fecdd3',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#ffe4e6',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '600',
    borderRadius: 8,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    headerBg: '#ffffff',
    headerText: '#1e293b',
    cellBg: '#ffffff',
    cellText: '#475569',
    borderColor: '#e2e8f0',
    borderWidth: 1,
    borderStyle: 'solid',
    fontFamily: 'Inter',
    fontSize: 14,
    headerFontWeight: '700',
    borderRadius: 0,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'elegant',
    name: 'Elegant',
    headerBg: '#1c1917',
    headerText: '#fafaf9',
    cellBg: '#ffffff',
    cellText: '#292524',
    borderColor: '#d6d3d1',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#f5f5f4',
    fontFamily: 'Playfair Display',
    fontSize: 15,
    headerFontWeight: '600',
    borderRadius: 4,
    stickyHeader: true,
    stickyFirstCol: false,
  },
  {
    id: 'neon',
    name: 'Neon',
    headerBg: '#000000',
    headerText: '#00ff88',
    cellBg: '#0a0a0a',
    cellText: '#00cc6a',
    borderColor: '#00ff88',
    borderWidth: 1,
    borderStyle: 'solid',
    alternateRowBg: '#111111',
    fontFamily: 'JetBrains Mono',
    fontSize: 13,
    headerFontWeight: '600',
    borderRadius: 0,
    stickyHeader: true,
    stickyFirstCol: false,
  },
];
